# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Coordinate Descend Algorithm for Compositional Data Lasso problem in Rcpp
#' @description Specific information can be found in 'r_cdmlasso' function(Pay attention that 'c_cdmlasso' only receive numeric vector and matrix as input which is different from 'r_cdmlasso')
#' @param y Response variable which is a n*1 vector
#' @param z Designed n*p matrix of composition as explanatory variables
#' @param lambda Regularization parameter in Lasso problem
#' @param mu Penalty parameter avoiding zero-sum constraint from affecting convergence(suggested to be 1)
#' @param tol Iteration stop condition: Tolerance
#' @param max_iter Iteration stop condition: Max iterations
#' @examples
#' \dontrun{
#' data(data)
#' y <- as.vector(unlist(data[1]))
#' z <- as.matrix(data[2:31])
#' mu <- 1; lambda <- 0.5
#' c_cdmlasso(y,z,lambda,mu)
#' }
#' @export
c_cdmlasso <- function(y, z, lambda, mu, tol = 1e-4, max_iter = 1000L) {
    .Call('_SA24204132_c_cdmlasso', PACKAGE = 'SA24204132', y, z, lambda, mu, tol, max_iter)
}

#' @title Tuning lambda assuming GIC to be a constant function in Rcpp
#' @description Specific information can be found in 'r_clambda' function(It has the same problem as 'c_cmdlasso' which means you need to make sure that y and z is numeric before using)
#' @param y Response variable which is a n*1 vector
#' @param z Designed n*p matrix of composition as explanatory variables
#' @param mu Penalty parameter avoiding zero-sum constraint from affecting convergence(suggested to be 1)
#' @param learning_rate Learning rate for upgrading grad function
#' @param max_iter Iteration stop condition: Max iterations
#' @param tol Iteration stop condition: Tolerance
#' @examples
#' \dontrun{
#' data(data)
#' y <- as.vector(unlist(data[1]))
#' z <- as.matrix(data[2:31])
#' mu <- 1
#' c_clambda(y,z,mu)
#' }
#' @export
c_clambda <- function(y, z, mu, learning_rate = 0.01, max_iter = 1000L, tol = 1e-6) {
    .Call('_SA24204132_c_clambda', PACKAGE = 'SA24204132', y, z, mu, learning_rate, max_iter, tol)
}

